matrix: 
  include: 
  - os: linux  
    name: "Full tests [Linux]"
    language: python
    dist: bionic
    env: PY=python3
    python: "3.7"
    install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda    
    - conda info -a  # Useful for debugging any issues with conda
    - conda create -n fenicsproject -c conda-forge fenics
    - conda activate fenicsproject
    
  - os: windows 
    name: "Mock tests [Windows]"
    # does not support python 
    language: bash 
    env: PY=py
    python: "3.5"
    before_install: choco install python --version 3.5.4 
    install: 
      - $PY -m pip install --upgrade pip
      - $PY -m pip install scipy 
      - $PY -m pip install --upgrade setuptools
      - $PY -m pip install wheel

  - os: linux
    name: "Systemtests"
    if: fork = false AND ( branch = master OR branch = develop )
    python: "3.6" 
    env: PY=python3
    script:
    - curl -LO --retry 3 https://raw.githubusercontent.com/precice/systemtests/master/trigger_systemtests.py
    - travis_wait 60 $PY trigger_systemtests.py --adapter fenics --wait

  - os: osx
    name: "Mock tests [OSx]"
    # does not support python
    language: generic 
    env: PY=python3
    install: 
      - pip3 install scipy

script: 
  - mkdir -p precice && echo -e "from setuptools import setup\nsetup(name='precice', version='2.0.0')" > precice/setup.py
  - $PY -m pip install ./precice/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then  $PY setup.py test ; else $PY setup.py test -s tests.test_fenicsadapter ; fi
